name = "«constrained-decoding-formalization»"
version = "0.1.0"
defaultTargets = ["ConstrainedDecodingFormalization"]

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "lean4export"
git = "https://github.com/leanprover/lean4export"
rev = "71f41350675895dda791b8ff9c1dfb77d18b3585"

[[require]]
name = "repl"
git = "https://github.com/leanprover-community/repl"
rev = "v4.29.0-rc6"

[[lean_lib]]
name = "ConstrainedDecodingFormalization"

moreLinkArgs = ["-L./.lake/packages/LeanCopilot/.lake/build/lib", "-lctranslate2"]
