name: Deploy dependency graph

on:
  push:
    branches:
      - main # Trigger on pushes to the default branch
  workflow_dispatch:        # Allow manual triggering of the workflow from the GitHub Actions interface

# Cancel previous runs if a new commit is pushed to the same PR or branch
concurrency:
  group: ${{ github.ref }}  # Group runs by the ref (branch or PR)
  cancel-in-progress: true  # Cancel any ongoing runs in the same group

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read  # Read access to repository contents
  pages: write    # Write access to GitHub Pages
  id-token: write # Write access to ID tokens

jobs:
  build_project:
    runs-on: ubuntu-latest
    name: Build dependency graph site
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Install elan
        run: curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y

      - name: Add elan to PATH
        run: echo "$HOME/.elan/bin" >> "$GITHUB_PATH"

      - name: Get Mathlib cache
        run: lake exe cache get || true

      - name: Cache mathlib API docs
        uses: actions/cache@v4
        with:
          path: |
            .lake/build/doc/Init
            .lake/build/doc/Lake
            .lake/build/doc/Lean
            .lake/build/doc/Std
            .lake/build/doc/Mathlib
            .lake/build/doc/declarations
            .lake/build/doc/find
            .lake/build/doc/*.*
            !.lake/build/doc/declarations/declaration-data-ConstrainedDecodingFormalization*
          key: MathlibDoc-${{ hashFiles('lake-manifest.json') }}
          restore-keys: MathlibDoc-

      - name: Build project API documentation
        run: lake -R -Kenv=dev build ConstrainedDecodingFormalization:docs

      - name: Build dependency graph website
        run: ./lean-dep-viz build --output-dir site

      - name: Copy API documentation to `site/docs`
        run: cp -r .lake/build/doc site/docs

      - name: Remove unnecessary lake files from documentation in `site/docs`
        run: |
          find site/docs -name "*.trace" -delete
          find site/docs -name "*.hash" -delete

      - name: Upload website
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Make sure the API documentation cache works
        run: mv site/docs .lake/build/doc
